### ISSUE TITLE
Supporting for multi-concept customization

### ISSUE THREAD

**Issue by zzhang2816** [zhangxulu1996/Compositional-Inversion#1]
Hey, it's really a great job. As you show in the paper, it has the capacibity to composite multiple learned objects("Figure 6: Examples of composing inverted concepts of cat*, chair*, dog*, and barn* to each other."). But I am not sure does the code released supporting multi-concept customization? Thank you!

**Comment by zhangxulu1996** [comment]
Thanks for your support!
The code supports multi-concept customization. To train multiple concepts in one model, you can run the following scripts: '/scripts/compositional_custom_diffusion_multi.sh' or '/scripts/compositional_dreambooth_multi.sh'. For now, we haven't support optimization-based approach for multi-concept composition in Custom Diffusion.

**Comment by zzhang2816** [comment]
I see. Thanks for your prompted reply!
