### ISSUE TITLE
About regularization images

### ISSUE THREAD

**Issue by boringKey** [zhangxulu1996/Compositional-Inversion#2]
Sorry to bother you. Unfortunately, the website containing regularization images has been shut down, which has troubled me for a long time. Could you please share your local real images with me in the form of a link? Thank you very much.

**Comment by zhangxulu1996** [comment]
You can download the regularization dataset we used from https://drive.google.com/file/d/13hl---5kpd7_cvv-p3E6j_PeAqeZWX9w/view?usp=sharing. Note that these images are from LAION-400M. Also, remember to check the image paths in "images.txt".
